<key>SUPublicDSAKeyFile</key>
<string>dsa_pub.pem</string>
<key>SUFeedURL</key>
<string>{feed}</string>
<key>CFBundleVersion</key>
<string>{version}</string>
<key>SUEnableAutomaticChecks</key>
<string>{autocheck}</string>
<key>SUAllowsAutomaticUpdates</key>
<string>{autoup}</string>
<key>SUEnableSystemProfiling</key>
<string>{profile}</string>
